apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: invoices-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: invoices-ui
  template:
    metadata:
      labels:
        app: invoices-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: invoices-ui
        ports:
        - containerPort: 80
  strategy:
    canary:
      canaryService: preview-invoices-ui
      steps:
      - setWeight: 50
      - pause: {}
