apiVersion: v1
kind: Service
metadata:
  name: invoices-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: invoices-ui
---
apiVersion: v1
kind: Service
metadata:
  name: preview-invoices-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: invoices-ui